spring:
  application:
    name: zipkin-server
  #datasource:
  #  schema: classpath:/mysql.sql
  #  url: jdbc:mysql://localhost:3306/Zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
  #  username: root
  #  password: root
  #  driver-class-name: com.mysql.jdbc.Driver
  #  initialize: true
  #  continue-on-error: true
  sleuth:
    enabled: false
#zipkin:
#  storage:
#    type: mysql
server:
  port: 9411
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_SERVICE_HOST:localhost}:${EUREKA_SERVER_SERVICE_PORT:8761}/eureka/
      #defaultZone: http://192.168.16.91:31423/eureka/
  
  instance: 
      prefer-ip-address: true
      hostname: ${ZIPKIN_SERVER_SERVICE_HOST:localhost}
      instanceId: ${spring.application.name}-${random.int}
      
#zipkin数据保存到数据库中需要进行如下配置
#表示当前程序不使用sleuth
#spring.sleuth.enabled=false
##表示zipkin数据存储方式是mysql
#zipkin.storage.type=mysql
##数据库脚本创建地址，当有多个是可使用[x]表示集合第几个元素
#spring.datasource.schema[0]=classpath:/mysql.sql
##spring boot数据源配置
#spring.datasource.url=jdbc:mysql://localhost:3306/zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.initialize=true
#spring.datasource.continue-on-error=true