server:
  port: 8765
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_SERVICE_HOST:localhost}:${EUREKA_SERVER_SERVICE_PORT:8761}/eureka/
      #defaultZone: http://192.168.16.91:31423/eureka/
  
  instance: 
      prefer-ip-address: true
      hostname: ${ZUUL_SERVICE_HOST:localhost}
      instanceId: ${spring.application.name}-${random.int}
      
#      defaultZone: http://localhost:8761/eureka
#  instance: 
#      prefer-ip-address: false
#      instanceId: ${spring.application.name}-${random.int}
#      
management:
  security:
    enabled: false

zuul:
  routes:
    a: 
      path: /a/**
      service-id: ribbon-hystrix
    b:
      path: /b/**
      service-id: feign-hystrix
    