FROM 192.168.7.123/poc/java

LABEL maintainer "xiaohuo.ren@daocloud.io"

COPY /project/target/microservice-consumer-b-1.5.9.RELEASE.jar  \
/usr/src/myapp/microservice-consumer-b-1.5.9.RELEASE.jar

WORKDIR /usr/src/myapp/

ENTRYPOINT java -jar microservice-consumer-b-1.5.9.RELEASE.jar
