apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-client
  labels:
    app: admin-client
spec:
  template:
    metadata:
      name: admin-client
      labels:
        app: admin-client
    spec:
      containers:
      - name: admin-client
        image: cargo.caicloudprivatetest.com/caicloud/admin-client:v4
        ports:
        - containerPort: 8789
---
apiVersion: v1
kind: Service
metadata:
  name: admin-client
spec:
  type: NodePort
  ports:
  - port: 8789
    targetPort: 8789
    #nodePort: 30061
  selector:
    app: admin-client
