apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bus-client
  labels:
    app: bus-client
spec:
  replicas: 2
  template:
    metadata:
      name: bus-client
      labels:
        app: bus-client
    spec:
      containers:
      - name: bus-client
        image: cargo.caicloudprivatetest.com/caicloud/bus-client:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 8711
---
apiVersion: v1
kind: Service
metadata:
  name: bus-client
spec:
  type: NodePort
  ports:
  - port: 8711
    targetPort: 8711
    #nodePort: 30061
  selector:
    app: bus-client
