apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  template:
    metadata:
      name: config-server
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: cargo.caicloudprivatetest.com/caicloud/config-server:v4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8798
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: NodePort
  ports:
  - port: 8798
    targetPort: 8798
    #nodePort: 30061
  selector:
    app: config-server
