apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-client
  labels:
    app: eureka-client
spec:
  replicas: 1
  template:
    metadata:
      name: eureka-client
      labels:
        app: eureka-client
    spec:
      containers:
      - name: eureka-client
        image: cargo.caicloudprivatetest.com/caicloud/eureka-client:v4
        ports:
        - containerPort: 8762
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-client
spec:
  type: NodePort
  ports:
  - port: 8762
    targetPort: 8762
    #nodePort: 30062
  selector:
    app: eureka-client

