apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: feign-hystrix
  labels:
    app: feign
spec:
  template:
    metadata:
      name: feign
      labels:
        app: feign
    spec:
      containers:
      - name: feign
        image: cargo.caicloudprivatetest.com/caicloud/feign-hystrix:v4
        ports:
        - containerPort: 8764
---
apiVersion: v1
kind: Service
metadata:
  name: feign-hystrix
spec:
  type: NodePort
  ports:
  - port: 8764
    targetPort: 8764
    #nodePort: 30061
  selector:
    app: feign
