apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-server
  labels:
    app: rabbitmq-server
spec:
  template:
    metadata:
      name: rabbitmq-server
      labels:
        app: rabbitmq-server
    spec:
      containers:
      - name: rabbitmq-server
        image: cargo.caicloudprivatetest.com/caicloud/rabbitmq:3-management
        ports:
        - containerPort: 8710
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-server
spec:
  type: NodePort
  ports:
  - name: port1
    port: 4379
    targetPort: 4379
  - name: port2
    port: 5671
    targetPort: 5671
  - name: port3
    port: 15671
    targetPort: 15671
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: http
    port: 15672
    targetPort: 15672
  - name: clustering
    port: 25672
    targetPort: 25672
  selector:
    app: rabbitmq-server
