apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: turbine
  labels:
    app: turbine
spec:
  template:
    metadata:
      name: turbine
      labels:
        app: turbine
    spec:
      containers:
      - name: turbine
        image: cargo.caicloudprivatetest.com/caicloud/turbine:v4
        ports:
        - containerPort: 8766
---
apiVersion: v1
kind: Service
metadata:
  name: turbine
spec:
  type: NodePort
  ports:
  - port: 8766
    targetPort: 8766
    #nodePort: 30061
  selector:
    app: turbine
