apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-server
  labels:
    app: zipkin-server
spec:
  template:
    metadata:
      name: zipkin-server
      labels:
        app: zipkin-server
    spec:
      containers:
      - name: zipkin-server
        image: cargo.caicloudprivatetest.com/caicloud/zipkin-server:v4
        ports:
        - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
spec:
  type: NodePort
  ports:
  - port: 9411
    targetPort: 9411
    #nodePort: 30061
  selector:
    app: zipkin-server
