apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-client
  labels:
    app: zipkin-client
spec:
  template:
    metadata:
      name: zipkin-client
      labels:
        app: zipkin-client
    spec:
      containers:
      - name: zipkin-client
        image: cargo.caicloudprivatetest.com/caicloud/zipkin-client:v4
        ports:
        - containerPort: 9412
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-client
spec:
  type: NodePort
  ports:
  - port: 9412
    targetPort: 9412
    #nodePort: 30061
  selector:
    app: zipkin-client
