apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zuul
  labels:
    app: zuul
spec:
  template:
    metadata:
      name: zuul
      labels:
        app: zuul
    spec:
      containers:
      - name: zuul
        image: cargo.caicloudprivatetest.com/caicloud/zuul:v4
        ports:
        - containerPort: 8765
---
apiVersion: v1
kind: Service
metadata:
  name: zuul
spec:
  type: NodePort
  ports:
  - port: 8765
    targetPort: 8765
    #nodePort: 30061
  selector:
    app: zuul
