server:
  port: 8764
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance: 
      prefer-ip-address: false
      instanceId: ${spring.application.name}:${server.port}-${random.int}
      
management:
  security:
    enabled: false

zuul:
  routes:
    a: 
      path: /a/**
      service-id: ribbonHystrix
    b:
      path: /b/**
      service-id: feignHystrix
    